import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import morgan from 'morgan';
import { config } from './config.js';
import { notFound, errorHandler } from './middleware/error.js';
import authRoutes from './routes/auth.routes.js';
import empleadosRoutes from './routes/empleados.routes.js';
import chsRoutes from './routes/chs.routes.js';
import personasRoutes from './routes/personas.routes.js';
import siradigRoutes from './routes/siradig.routes.js';
import acumuladoresRoutes from './routes/acumuladores.routes.js';
import embargosRoutes from './routes/embargos.routes.js';
import dashboardRoutes from './routes/dashboard.routes.js';
import alertasRoutes from './routes/alertas.routes.js';
import provisionRoutes from './routes/provision.routes.js';
import valoresLegalesRoutes from './routes/valoresLegales.routes.js';
import mailRoutes from './routes/mail.routes.js';
import novedadesRoutes from './routes/novedades.routes.js';
import vacacionesRoutes from './routes/vacaciones.routes.js';
import legajoRoutes from './routes/legajo.routes.js';
import mensajesRoutes from './routes/mensajes.routes.js';
import cbusRoutes from './routes/cbus.routes.js';
import gananciasRoutes from './routes/ganancias.routes.js';
import escalaRoutes from './routes/escala.routes.js';
import conveniosRoutes from './routes/convenios.routes.js';
import artRoutes from './routes/art.routes.js';
import reportesRoutes from './routes/reportes.routes.js';
import sindicatosRoutes from './routes/sindicatos.routes.js';
import hysRoutes from './routes/hys.routes.js';
import reglamentoRoutes from './routes/reglamento.routes.js';
import cierresRoutes from './routes/cierres.routes.js';
import anticiposRoutes from './routes/anticipos.routes.js';
import aprobacionesRoutes from './routes/aprobaciones.routes.js';
import parametrosRoutes from './routes/parametros.routes.js';
import conceptosRoutes from './routes/conceptos.routes.js';
import liquidacionRoutes from './routes/liquidacion.routes.js';
import produccionRoutes from './routes/produccion.routes.js';
import recibosRoutes from './routes/recibos.routes.js';
import licenciasRoutes from './routes/licencias.routes.js';
import sancionesRoutes from './routes/sanciones.routes.js';
import evaluacionesRoutes from './routes/evaluaciones.routes.js';
import certificadosRoutes from './routes/certificados.routes.js';
import adminRoutes from './routes/admin.routes.js';
import elementosRoutes from './routes/elementos.routes.js';
import beneficiosRoutes from './routes/beneficios.routes.js';
import domicilioRoutes from './routes/domicilio.routes.js';
import familiaresRoutes from './routes/familiares.routes.js';
import fichadasRoutes from './routes/fichadas.routes.js';
import prosoftRoutes from './routes/prosoft.routes.js';
import delegacionesRoutes from './routes/delegaciones.routes.js';
import arcaRoutes from './routes/arca.routes.js';
import obraSocialRoutes from './routes/obraSocial.routes.js';
import puestosRoutes from './routes/puestos.routes.js';
import camposRoutes from './routes/campos.routes.js';
import valoresAuxRoutes from './routes/valoresAux.routes.js';
import plantillasRoutes from './routes/plantillas.routes.js';
import modeloReciboRoutes from './routes/modeloRecibo.routes.js';
import agrupacionesRoutes from './routes/agrupaciones.routes.js';
import configHistRoutes from './routes/configHist.routes.js';
import reclutamientoRoutes from './routes/reclutamiento.routes.js';
import desempenoRoutes from './routes/desempeno.routes.js';
import compensacionesRoutes from './routes/compensaciones.routes.js';
import lmsRoutes from './routes/lms.routes.js';
import desarrolloRoutes from './routes/desarrollo.routes.js';
import comunicacionesRoutes from './routes/comunicaciones.routes.js';
import fichajeWebRoutes from './routes/fichajeWeb.routes.js';
import firmasRoutes from './routes/firmas.routes.js';
import miFormacionRoutes from './routes/miFormacion.routes.js';
import miFeedbackRoutes from './routes/miFeedback.routes.js';
import iaRoutes from './routes/ia.routes.js';
import sicoreRoutes from './routes/sicore.routes.js';
import matrizAntiguedadRoutes from './routes/matrizAntiguedad.routes.js';
import modalidadesRoutes from './routes/modalidades.routes.js';
import competenciasRoutes from './routes/competencias.routes.js';
import unidadesRoutes from './routes/unidades.routes.js';
import posicionesRoutes from './routes/posiciones.routes.js';
import workflowsRoutes from './routes/workflows.routes.js';
import talentoRoutes from './routes/talento.routes.js';
import formacionRoutes from './routes/formacion.routes.js';
import encuestasRoutes from './routes/encuestas.routes.js';

export function createApp() {
  const app = express();
  // Detrás del nginx/reverse-proxy: confiar en X-Forwarded-* para IP real (rate-limit) y HTTPS.
  app.set('trust proxy', Number(process.env.TRUST_PROXY || 1));
  app.use(helmet());
  // CORS: si el origen es '*' no se pueden enviar credenciales (regla del navegador).
  app.use(cors({ origin: config.corsOrigin, credentials: config.corsOrigin !== '*' }));
  app.use(express.json({ limit: '5mb' }));
  app.use(morgan('dev'));

  app.get('/api/health', (req, res) => res.json({ ok: true, ts: new Date().toISOString() }));
  app.use('/api/auth', authRoutes);
  app.use('/api/empleados', empleadosRoutes);
  app.use('/api/mensajes', mensajesRoutes);
  app.use('/api/cbus', cbusRoutes);
  app.use('/api/ganancias', gananciasRoutes);
  app.use('/api/escala', escalaRoutes);
  app.use('/api/convenios', conveniosRoutes);
  app.use('/api/art', artRoutes);
  app.use('/api/reportes', reportesRoutes);
  app.use('/api/sindicatos', sindicatosRoutes);
  app.use('/api/hys', hysRoutes);
  app.use('/api/reglamento', reglamentoRoutes);
  app.use('/api/cierres', cierresRoutes);
  app.use('/api/anticipos', anticiposRoutes);
  app.use('/api/aprobaciones', aprobacionesRoutes);
  app.use('/api/parametros', parametrosRoutes);
  app.use('/api/conceptos', conceptosRoutes);
  app.use('/api/liquidacion', liquidacionRoutes);
  app.use('/api/produccion', produccionRoutes);
  app.use('/api/recibos', recibosRoutes);
  app.use('/api/licencias', licenciasRoutes);
  app.use('/api/sanciones', sancionesRoutes);
  app.use('/api/evaluaciones', evaluacionesRoutes);
  app.use('/api/certificados', certificadosRoutes);
  app.use('/api/admin', adminRoutes);
  app.use('/api/elementos', elementosRoutes);
  app.use('/api/beneficios', beneficiosRoutes);
  app.use('/api/cambios-domicilio', domicilioRoutes);
  app.use('/api/cambios-obra-social', obraSocialRoutes);
  app.use('/api/puestos', puestosRoutes);
  app.use('/api/campos', camposRoutes);
  app.use('/api/valores-aux', valoresAuxRoutes);
  app.use('/api/plantillas-legajo', plantillasRoutes);
  app.use('/api/modelo-recibo', modeloReciboRoutes);
  app.use('/api/agrupaciones', agrupacionesRoutes);
  app.use('/api/config-hist', configHistRoutes);
  app.use('/api/reclutamiento', reclutamientoRoutes);
  app.use('/api/desempeno', desempenoRoutes);
  app.use('/api/compensaciones', compensacionesRoutes);
  app.use('/api/lms', lmsRoutes);
  app.use('/api/desarrollo', desarrolloRoutes);
  app.use('/api/comunicaciones', comunicacionesRoutes);
  app.use('/api/fichaje', fichajeWebRoutes);
  app.use('/api/firmas', firmasRoutes);
  app.use('/api/mi-formacion', miFormacionRoutes);
  app.use('/api/mi-feedback', miFeedbackRoutes);
  app.use('/api/ia', iaRoutes);
  app.use('/api/sicore', sicoreRoutes);
  app.use('/api/matriz-antiguedad', matrizAntiguedadRoutes);
  app.use('/api/modalidades', modalidadesRoutes);
  app.use('/api/competencias', competenciasRoutes);
  app.use('/api/unidades', unidadesRoutes);
  app.use('/api/posiciones', posicionesRoutes);
  app.use('/api/workflows', workflowsRoutes);
  app.use('/api/talento', talentoRoutes);
  app.use('/api/formacion', formacionRoutes);
  app.use('/api/encuestas', encuestasRoutes);
  app.use('/api/arca', arcaRoutes);
  app.use('/api/familiares', familiaresRoutes);
  app.use('/api/fichadas', fichadasRoutes);
  app.use('/api/prosoft', prosoftRoutes);
  app.use('/api/delegaciones', delegacionesRoutes);
  app.use('/api/chs', chsRoutes);
  app.use('/api/personas', personasRoutes);
  app.use('/api/siradig', siradigRoutes);
  app.use('/api/acumuladores', acumuladoresRoutes);
  app.use('/api/embargos', embargosRoutes);
  app.use('/api/dashboard', dashboardRoutes);
  app.use('/api/alertas', alertasRoutes);
  app.use('/api/provision', provisionRoutes);
  app.use('/api/valores-legales', valoresLegalesRoutes);
  app.use('/api/mail', mailRoutes);
  app.use('/api/novedades', novedadesRoutes);
  app.use('/api/vacaciones', vacacionesRoutes);
  app.use('/api/legajo-docs', legajoRoutes);

  app.use(notFound);
  app.use(errorHandler);
  return app;
}
